### ISSUE TITLE
Question: How do I import it via the CDN link?

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [voelza/plateJS#1]
Not sure how to. I have just copied the source over to a file in my Vite project for the time being. Any help would be appreciated!

**Comment by voelza** [comment]
Hi,
I have to confess: I didn't think someone would be actually using this already. Haha.
The CDN link does not work at the moment because I didn't release version 0.1.0 yet. I found a few bugs while implementing the 7GUIs examples. I still have a few tasks left. I will probably release the version when I got that done. 
So beware while using it.

**Comment by jaymanmatthewsdev** [comment]
No worries, I managed to create a very simple, unstyled todo list example but I noticed that all elements in the `forEach` are re-rendered every time in the DOM which could become very imperformant, any plans to manage that behaviour?

**Comment by voelza** [comment]
Yeaaah... I know. This was the simplest solution to do this. I plan on making it more efficient.
There are also some other weird parts in this you might encounter. I will fix/improve them as I start encounter them myself. Feel free to report any other weirdness you find.

**Comment by voelza** [comment]
Hi,
I just released version 0.1.0! The CDN should work now. 
I also improved the `forEach` rerendering. Hope it performs better now.
